// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe39_0i2VQPHyGl2WDNHloFlM_4Ta8Hhk',
    appId: '1:848163845360:web:38b28a6bd07cf2688c7e35',
    messagingSenderId: '848163845360',
    projectId: 'growise-95ce0',
    authDomain: 'growise-95ce0.firebaseapp.com',
    storageBucket: 'growise-95ce0.appspot.com',
    measurementId: 'G-CM0RT13Q84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-gATOnhwuIahQTBP-dRyCIwAn71KgqGg',
    appId: '1:848163845360:android:3e0f369581e085988c7e35',
    messagingSenderId: '848163845360',
    projectId: 'growise-95ce0',
    storageBucket: 'growise-95ce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT-1fjU0PNUT1Uf3D8qdQ6Lhoz11qEQPo',
    appId: '1:848163845360:ios:4ae7d31ecc9a62d68c7e35',
    messagingSenderId: '848163845360',
    projectId: 'growise-95ce0',
    storageBucket: 'growise-95ce0.appspot.com',
    iosBundleId: 'com.example.growise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT-1fjU0PNUT1Uf3D8qdQ6Lhoz11qEQPo',
    appId: '1:848163845360:ios:4ae7d31ecc9a62d68c7e35',
    messagingSenderId: '848163845360',
    projectId: 'growise-95ce0',
    storageBucket: 'growise-95ce0.appspot.com',
    iosBundleId: 'com.example.growise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe39_0i2VQPHyGl2WDNHloFlM_4Ta8Hhk',
    appId: '1:848163845360:web:b18c069ceb906fe68c7e35',
    messagingSenderId: '848163845360',
    projectId: 'growise-95ce0',
    authDomain: 'growise-95ce0.firebaseapp.com',
    storageBucket: 'growise-95ce0.appspot.com',
    measurementId: 'G-MSZRB4V8RT',
  );

}